const KEY='lifegame:local-scores';
function readSetting(){try{return(localStorage.getItem('lifegame:server-url')||window.LIFEGAME_SERVER_URL||'').trim()}catch{return String(window.LIFEGAME_SERVER_URL||'').trim()}}
function httpBase(){return readSetting().replace(/^wss:/,'https:').replace(/^ws:/,'http:').replace(/\/$/,'')}
export function serverUrl(){return readSetting()}
export function setServerUrl(url){const value=String(url||'').trim().replace(/\/$/,'');try{if(value)localStorage.setItem('lifegame:server-url',value);else localStorage.removeItem('lifegame:server-url')}catch{};return value}
export function localScores(gameSlug){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');return Array.isArray(all[gameSlug])?all[gameSlug].sort((a,b)=>b.score-a.score).slice(0,20):[]}catch{return[]}}
export function saveLocal(gameSlug,name,score){let all={};try{all=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};const rows=Array.isArray(all[gameSlug])?all[gameSlug]:[];rows.push({name:String(name||'Player').slice(0,24),score:Math.max(0,Math.round(score||0)),at:new Date().toISOString()});all[gameSlug]=rows.sort((a,b)=>b.score-a.score).slice(0,50);try{localStorage.setItem(KEY,JSON.stringify(all))}catch{};return all[gameSlug]}
export async function globalScores(gameSlug,period='all'){const base=httpBase();if(!base)return{connected:false,rows:[],message:'Serveur mondial non configuré.'};try{const response=await fetch(base+'/api/leaderboards?game='+encodeURIComponent(gameSlug)+'&period='+encodeURIComponent(period),{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json();return{connected:true,rows:Array.isArray(data.rows)?data.rows:[],message:''}}catch{return{connected:false,rows:[],message:'Serveur mondial indisponible.'}}}
export async function submitScore(gameSlug,name,score,duration){saveLocal(gameSlug,name,score);const base=httpBase();if(!base)return{connected:false};try{const response=await fetch(base+'/api/scores',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gameSlug,name:String(name||'Player').slice(0,24),score:Math.max(0,Math.round(score||0)),duration:Math.max(0,Math.round(duration||0))})});return{connected:response.ok}}catch{return{connected:false}}}
export async function onlinePlayers(){const base=httpBase();if(!base)return{connected:false,players:[]};try{const response=await fetch(base+'/api/online',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();return{connected:true,players:Array.isArray(data.players)?data.players:[]}}catch{return{connected:false,players:[]}}}
