const KEY='lifegame:local-scores';
function httpBase(){const raw=(localStorage.getItem('lifegame:server-url')||window.LIFEGAME_SERVER_URL||'').trim();if(!raw)return'';return raw.replace(/^wss:/,'https:').replace(/^ws:/,'http:').replace(/\/$/,'')}
export function serverUrl(){return(localStorage.getItem('lifegame:server-url')||window.LIFEGAME_SERVER_URL||'').trim()}
export function setServerUrl(url){const v=String(url||'').trim().replace(/\/$/,'');if(v)localStorage.setItem('lifegame:server-url',v);else localStorage.removeItem('lifegame:server-url');return v}
export function localScores(gameSlug){try{const all=JSON.parse(localStorage.getItem(KEY)||'{}');return(all[gameSlug]||[]).sort((a,b)=>b.score-a.score).slice(0,20)}catch{return[]}}
export function saveLocal(gameSlug,name,score){let all={};try{all=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};const rows=all[gameSlug]||[];rows.push({name:String(name||'Player').slice(0,24),score:Math.max(0,Math.round(score)),at:new Date().toISOString()});all[gameSlug]=rows.sort((a,b)=>b.score-a.score).slice(0,50);localStorage.setItem(KEY,JSON.stringify(all));return all[gameSlug]}
export async function globalScores(gameSlug,period='all'){const base=httpBase();if(!base)return{connected:false,rows:[],message:'Serveur mondial non configuré.'};try{const r=await fetch(base+'/api/leaderboards?game='+encodeURIComponent(gameSlug)+'&period='+encodeURIComponent(period),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();return{connected:true,rows:Array.isArray(data.rows)?data.rows:[],message:''}}catch(e){return{connected:false,rows:[],message:'Serveur mondial indisponible.'}}}
export async function submitScore(gameSlug,name,score,duration){const base=httpBase();saveLocal(gameSlug,name,score);if(!base)return{connected:false};try{const r=await fetch(base+'/api/scores',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({gameSlug,name,score,duration})});return{connected:r.ok}}catch{return{connected:false}}}
export async function onlinePlayers(){const base=httpBase();if(!base)return{connected:false,players:[]};try{const r=await fetch(base+'/api/online',{cache:'no-store'});if(!r.ok)throw new Error();const data=await r.json();return{connected:true,players:data.players||[]}}catch{return{connected:false,players:[]}}}
